services:
  db_flash:
    container_name: db_flash
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5433:5433
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: flash_card
      PGDATA: /data/postgres/db_flash
    volumes:
      - db_flash:/data/postgres/db_flash
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d flash_card" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  db_flash:
